Acta de mayo
python-spain/documentacion pull request #17
Opened 2019-05-28 05:14 UTC by maigimenez

El acta de mayo lista para ser revisada.

2019-05-28 13:53 UTC, mariocj89 approved these changes

2019-05-28 14:54 UTC, astrojuanlu requested changes
¡Gracias @maigimenez! He puesto un comentario sobre un matiz importante.

2019-05-28 14:54 UTC, Juanlu001 commented on acta-2019-05-20.rst
> + Esta misma comisión deberá establecer unos mínimos de calidad y exigirlos a las futuras organizaciones locales.
¿En vez de "exigir" podemos reformular esto tipo "y trabajará con las futuras organizaciones locales para que se cumplan"? También en línea con la convocatoria oficial

https://comunidad.es.python.org/t/creacion-grupo-de-trabajo-pycones/132

Es decir, o cambiamos la convocatoria o cambiamos el acta, pero yo veo una discrepancia ahí

2019-07-14 08:30 UTC, maigimenez commented on acta-2019-05-20.rst
> + Esta misma comisión deberá establecer unos mínimos de calidad y exigirlos a las futuras organizaciones locales.
Tienes toda la razón. 
¡Acta cambiada!

2019-07-14 09:11 UTC, astrojuanlu approved these changes

2019-07-14 09:11 UTC, merged