Acta de la Asamblea General del 2018
python-spain/documentacion pull request #18
Opened 2019-10-01 12:44 UTC by maigimenez

Con muchísimo retraso, pero aquí está el acta de la asamblea general.

2019-10-01 13:43 UTC, astrojuanlu approved these changes

2019-10-07 10:11 UTC, mariocj89 requested changes

2019-10-07 10:11 UTC, mariocj89 commented on acta-2018-10-06-asamblea-general.rst
> + 1. Propuesta para integrar nuevos [niveles](https://github.com/python-spain/actas/pull/4) de miembros de la asociación.
This is rst, these links do not work :)

2019-10-07 11:57 UTC, maigimenez commented on acta-2018-10-06-asamblea-general.rst
> + 1. Propuesta para integrar nuevos [niveles](https://github.com/python-spain/actas/pull/4) de miembros de la asociación.
Indeed! Thanks!

2019-10-07 13:14 UTC, mariocj89 approved these changes

2019-10-07 13:58 UTC, merged