Monográfico sobre los canales de comunicación
python-spain/documentacion pull request #3
Opened 2018-05-10 16:45 UTC by maigimenez

Borrador pendiente de ser confirmado de la última reunión de la Junta Directiva de Python España que abordó el monográfico de los canales de comunicación.

2018-05-11 09:02 UTC, astrojuanlu requested changes
Está genial el acta, nada más he puesto algunos comentarios.

2018-05-11 09:02 UTC, Juanlu001 commented on acta-2018-05-08-comunicacion.rst
> +Como punto positivo, se trata de un canal con una gran cantidad de usuarios que nos gustaría que nos acompañan en el futuro creando una comunidad más diversa y activa.
nos gustaría que nos *acompañaran?

2018-05-11 09:02 UTC, Juanlu001 commented on acta-2018-05-08-comunicacion.rst
> + El disponer de plataformas multicanales facilita la gestión de las mismas.
plataformas *multicanal?

2018-05-11 09:02 UTC, Juanlu001 commented on acta-2018-05-08-comunicacion.rst
> + Se plantea, por lo tanto, que es más interesante para la comunidad, si continuar con el canal de Telegram o reconducir a los usuarios a otra plataforma.
*qué es más importante (si no la frase se lee rara)

2018-05-11 09:02 UTC, Juanlu001 commented on acta-2018-05-08-comunicacion.rst
> + Bien es cierto, que el canal de Telegram es una parte importante de la comunidad de Python España aunque ahora mismo es muy difícil de gestionar porque esta responsabilidad cae sobre una única perso
Yo quitaría "Bien es cierto, que "

2018-05-11 09:02 UTC, Juanlu001 commented on acta-2018-05-08-comunicacion.rst
> + En este sentido, se propone que se creen grupos de trabajos para gestionar las distintas tareas dentro de la comunidad como se hace en muchas otras comunidades. Esto nos permitirá crecer y abordar n
Yo aclararía que ahora se pueden crear grupos de trabajo de una manera más informal, pero que se plantea hacer un cambio real en el reglamento de la asociación de cara a la siguiente Asamblea General.

2018-05-11 09:02 UTC, Juanlu001 commented on acta-2018-05-08-comunicacion.rst
> + En este sentido, se propone que se creen grupos de trabajos para gestionar las distintas tareas dentro de la comunidad como se hace en muchas otras comunidades. Esto nos permitirá crecer y abordar n
Y también mencionaría el precedente del equipo editor de la web

2018-05-12 16:41 UTC, maigimenez commented on acta-2018-05-08-comunicacion.rst
> +Como punto positivo, se trata de un canal con una gran cantidad de usuarios que nos gustaría que nos acompañan en el futuro creando una comunidad más diversa y activa.
Toda la razón del mundo.

2018-05-12 16:42 UTC, maigimenez commented on acta-2018-05-08-comunicacion.rst
> + Se plantea, por lo tanto, que es más interesante para la comunidad, si continuar con el canal de Telegram o reconducir a los usuarios a otra plataforma.
¡Cierto! Mira que a mi también me sonaba raro, pero no sabía arreglarlo.

2018-05-12 16:51 UTC, maigimenez commented on acta-2018-05-08-comunicacion.rst
> + Bien es cierto, que el canal de Telegram es una parte importante de la comunidad de Python España aunque ahora mismo es muy difícil de gestionar porque esta responsabilidad cae sobre una única perso
Ok.

2018-05-12 17:06 UTC, maigimenez commented on acta-2018-05-08-comunicacion.rst
> + En este sentido, se propone que se creen grupos de trabajos para gestionar las distintas tareas dentro de la comunidad como se hace en muchas otras comunidades. Esto nos permitirá crecer y abordar n
Toda la razón. Lo he vuelto a redactar y he añadido el siguiente párrafo (te lo dejo aquí para que lo encuentres más fácil en la siguiente versión):

> En este sentido, se propone que se creen grupos de trabajos para gestionar las distintas tareas dentro de la comunidad como se hace en muchas otras comunidades Esto nos permitirá crecer y abordar nuevos objetivos. Ahora mismo existe un grupo de trabajo que se encarga de la edición de la web. De forma análoga, se plantea constituir un grupo de trabajo que se encargue de la comunicación. 

> En cualquier caso, se planetea hacer un cambio real en el reglamento de la asociación de cara a la siguiente Asamblea General que incluya el funcionamiento de los grupos de trabajo y que deberá ser refrendado por todos los miembros de la asociación.

2018-05-13 05:25 UTC, astrojuanlu approved these changes

2018-05-13 05:29 UTC, Juanlu001 commented
Por mí está bien, @python-spain/junta-directiva echad un vistazo y si no hay comentarios mergeamos en la siguiente reunión.

2018-05-14 16:12 UTC, mariocj89 approved these changes

2018-05-14 16:12 UTC, mariocj89 commented on acta-2018-05-08-comunicacion.rst
> +  Al introducir la encuesta en el canal general Python España se desencadenó una discusión muy difícil de gestionar, en la que unos pocos usuarios dominaron la conversación y nos fue realmente compli
Picky comment. 2 spacios aqui

2018-05-15 20:32 UTC, mabeldelgadob reviewed
Por mi parte todo bien.

2018-05-15 20:32 UTC, mabeldelgadob approved these changes

2018-05-23 20:35 UTC, maigimenez commented on acta-2018-05-08-comunicacion.rst
> +  Al introducir la encuesta en el canal general Python España se desencadenó una discusión muy difícil de gestionar, en la que unos pocos usuarios dominaron la conversación y nos fue realmente compli
¡Toda la razón! Es un error y lo arreglamos, de picky nada. :)

2018-05-24 20:17 UTC, mariocj89 approved these changes

2018-06-08 05:04 UTC, merged