Acta Febrero 2020.
python-spain/documentacion pull request #34
Opened 2020-02-16 17:21 UTC by raulcd

2020-02-16 18:41 UTC, dukebody requested changes
- Cambiar "Jesús Bameda" → "David Barragán".
- No es bloqueante, pero quizá podemos añadir en "ruegos y preguntas" mi petición sobre las cuentas de la asociación.

El resto de comentarios que he hecho son sólo sobre el estado de ciertas tareas. :)

2020-02-16 18:41 UTC, dukebody commented on actas/acta-2020-02-11.rst
> + Marcos se encargará de dar acceso a secretario y presidente al sistema actual.
@marcosgabarda ¿puedes hacer esto?

2020-02-16 18:41 UTC, dukebody commented on actas/acta-2020-02-11.rst
> +    Socia o socio                 Número
@raulcd @marcosgabarda ¿Se ha enviado mail a estos socios con su número y dado de alta en Discourse y Telegram? Entiendo que desde el correo de secretaría aun no podemos, pero al menos desde el de tesorería sí. Si no, lo hacemos desde nuestras cuentas personales.

2020-02-16 18:41 UTC, dukebody commented on actas/acta-2020-02-11.rst
> + Yamila realiza un resumen de la situación actual después de haber consultado con Jesús Bameda.
```suggestion
 Yamila realiza un resumen de la situación actual después de haber consultado con David Barragán.
```

2020-02-16 18:41 UTC, dukebody commented on actas/acta-2020-02-11.rst
> + No hay ruegos ni preguntas.
Es cierto que quedó un poco difuso, pero sí que hubo una pregunta por mi parte sobre el estado de cuentas de la asociación. Quedó una tarea para @marcosgabarda de compartirnos este estado de las cuentas, con la finalidad a medio plazo de hacer una propuesta de presupuesto para 2020.

Ya tenemos un informe a nivel PyConES 2019 pero haría falta uno más general de toda la asociación.

2020-02-16 18:44 UTC, dukebody commented on actas/acta-2020-02-11.rst
> + Se discute el proceso de alta existente y se plantea la posibilidad de gestionar el alta sin necesidad
@raulcd ¿Has podido averiguar algo sobre si hace falta aprobar las nuevas personas socias en Junta? Si no, podemos preguntar a la asesoría. En nuestros estatutos yo no he visto ninguna obligación al respecto y en otras asociaciones hemos incorporado socios sin necesidad de aprobarlos en junta.

2020-02-16 19:06 UTC, dukebody commented on actas/acta-2020-02-11.rst
> + Se aprueba por unanimidad el alta de los siguientes socios:
Creo recordar que @XaviTorello dijo algo de algunos socios de Girona que se apuntaron pero nunca recibieron confirmación. @XaviTorello, ¿has conseguido averiguar algo?

2020-02-17 09:35 UTC, raulcd commented on actas/acta-2020-02-11.rst
> +    Socia o socio                 Número
Yo no tengo acceso al correo.

2020-02-17 23:57 UTC, XaviTorello commented on actas/acta-2020-02-11.rst
> + Se aprueba por unanimidad el alta de los siguientes socios:
Lo hablamos en el sistema de discusiones mejor

2020-02-17 23:59 UTC, XaviTorello approved these changes
Thxs @raulcd, con los cambios propuestos por @dukebody lo veo bien 👍

2020-02-18 23:00 UTC, dukebody approved these changes

2020-02-18 23:01 UTC, merged