Versión inicial de acta 2020-03-03
python-spain/documentacion pull request #35
Opened 2020-03-14 17:36 UTC by dukebody

2020-03-16 12:07 UTC, raulcd requested changes

2020-03-16 12:07 UTC, raulcd commented on actas/acta-2020-03-03.rst
> +- Raúl y marcos revisarán dónde llegan los correos de alta@es….
typo `Marcos`

2020-03-16 12:07 UTC, raulcd commented on actas/acta-2020-03-03.rst
> +En la ciudad de Barcelona, Madrid, Valencia y Ordino siendo las 18:30 horas del 11 de febrero de 2020 y en única convocatoria, se celebra la reunión de la Junta Directiva de Python España.
Si queremos ser escrúpulosos hay que añadir Mallorca.

2020-03-16 12:07 UTC, raulcd commented on actas/acta-2020-03-03.rst
> +- La difusión de eventos relacionados no requerirá petición de aprobación por parte de la Junta, sino que será suficiente contactar a las personas encargadas de la difusión en la Asociación por redes
Estás seguro de que ésto quedó así, yo creo que quedamos en que se tenía que contactar con alguien de la junta (yo diría, presidente, vicepresidente, tesorero).

2020-03-16 20:22 UTC, dukebody commented on actas/acta-2020-03-03.rst
> +En la ciudad de Barcelona, Madrid, Valencia y Ordino siendo las 18:30 horas del 11 de febrero de 2020 y en única convocatoria, se celebra la reunión de la Junta Directiva de Python España.
Uy sí, es que lo copié tal cual del acta anterior y luego se me olvidó cambiarlo. Y la convocatoria fue a las 19h.

2020-03-16 20:22 UTC, dukebody commented on actas/acta-2020-03-03.rst
> +- La difusión de eventos relacionados no requerirá petición de aprobación por parte de la Junta, sino que será suficiente contactar a las personas encargadas de la difusión en la Asociación por redes
No lo tengo 100% claro ahora mismo. @python-spain/junta-directiva ?

También hay que arreglar la errata de "TWitter".

2020-03-16 20:23 UTC, dukebody commented
@raulcd ¿Puedes hacer los cambios tú una vez hayamos resuelto el tema de qué tipo de aprobación necesita la difusión de eventos?

2020-03-16 20:24 UTC, dukebody commented on actas/acta-2020-03-03.rst
> +- La difusión de eventos relacionados no requerirá petición de aprobación por parte de la Junta, sino que será suficiente contactar a las personas encargadas de la difusión en la Asociación por redes
Sobre "difusión", piensa que por ejemplo ahora @bameda hace retweets de muchos tweets sobre cosas interesantes de otras cuentas, incluyendo eventos, y no pasa por Junta. Supongo que no es lo mismo hacer difusión mediante RTs o hacer una campaña específica sobre un evento, no sé. ¿Opiniones?

2020-03-16 20:34 UTC, raulcd commented on actas/acta-2020-03-03.rst
> +- La difusión de eventos relacionados no requerirá petición de aprobación por parte de la Junta, sino que será suficiente contactar a las personas encargadas de la difusión en la Asociación por redes
Ostia, lo había leído mal. Pensaba que era la aprobación de los 200€ y había flipado. No, está bien, es que no lo había entendido bien. Arreglo el par de typos y le damos.

2020-03-17 17:45 UTC, raulcd approved these changes

2020-03-17 17:45 UTC, merged