Update codigo-conducta.rst
python-spain/documentacion pull request #38
Opened 2020-04-26 11:46 UTC by yamila-moreno

Los cambios respecto al pr #36 

- el índice cambia un poco el orden y los apartados
- se ha simplificado un poco el lenguaje

En general el contenido está tal cual, salvo pequeñas modificaciones.

2020-04-26 14:40 UTC, dukebody commented on codigo-conducta.rst
> +Nuestro estándares
```suggestion
Nuestros estándares
```

2020-04-26 14:40 UTC, dukebody commented on codigo-conducta.rst
> +* Presta especial atención a las personas que recién llegan a la comunidad
Erratas/gramática:

User... dé
Prestar...

2020-04-26 14:40 UTC, dukebody commented on codigo-conducta.rst
> +
```suggestion
La administración de la comunidad es responsable de aclarar y hacer cumplir este código de conducta; en caso de que se determine un comportamiento inadecuado, tomará las acciones que considere oportunas. Éstas van desde exigir el cese del comportamiento, hasta la expulsión de una persona de un evento o de la Asociación, sin derecho a reembolso.
```

He añadido lo de explusión  sin derecho a reembolso para que quede claro, que son condiciones que se aceptan al participar en un evento, y que luego no venga nadie pidiendo sus €s.

2020-04-26 14:40 UTC, dukebody commented on codigo-conducta.rst
> +Todas las personas administradoras de la comunidad están obligadas a respetar la privacidad y la seguridad de quienes denuncien incidentes.
@bameda proponía en https://github.com/python-spain/documentacion/pull/36#issuecomment-616184866 la posibilidad de realizar denuncias anónimas. ¿Deberíamos contemplar este caso aquí @yamila-moreno ?

2020-04-26 16:11 UTC, yamila-moreno commented on codigo-conducta.rst
> +* Presta especial atención a las personas que recién llegan a la comunidad
Anotado, lo corrijo!

2020-04-26 16:13 UTC, yamila-moreno commented on codigo-conducta.rst
> +Todas las personas administradoras de la comunidad están obligadas a respetar la privacidad y la seguridad de quienes denuncien incidentes.
Si resulta útil sí que lo pondría como mecanismo; no me queda claro cómo implementarlo para que sea anónimo.

2020-04-26 16:16 UTC, yamila-moreno commented
Gracias por la revisión @dukebody

2020-04-26 16:50 UTC, bameda commented on codigo-conducta.rst
> +Todas las personas administradoras de la comunidad están obligadas a respetar la privacidad y la seguridad de quienes denuncien incidentes.
Un form de google docs (u otro servicio similar) que sólo permita rellenar un campo de texto y que envíe las respuestas a coc@es.python.org

2020-04-26 16:52 UTC, bameda commented on codigo-conducta.rst
> +Todas las personas administradoras de la comunidad están obligadas a respetar la privacidad y la seguridad de quienes denuncien incidentes.
Un ejemplo 
![image](https://user-images.githubusercontent.com/877218/80314036-0b9d1980-87ef-11ea-9340-d5313db9f2bb.png)

2020-05-04 19:29 UTC, bameda requested changes
:+1: Me gusta.

2020-05-04 19:29 UTC, bameda commented on codigo-conducta.rst
> +Al participar en la comunidad de Python España, te comprometes a fomentar una experiencia libre de acoso para todo el mundo, independientemente de la edad, dimensión corporal, minusvalía visible o in
s/minusvalía/discapacidad/

2020-05-05 17:34 UTC, yamila-moreno commented on codigo-conducta.rst
> +Al participar en la comunidad de Python España, te comprometes a fomentar una experiencia libre de acoso para todo el mundo, independientemente de la edad, dimensión corporal, minusvalía visible o in
done!

2020-05-05 17:39 UTC, bameda approved these changes

2020-05-05 17:42 UTC, dukebody approved these changes

2020-05-05 18:31 UTC, merged