Acta Mayo 2020.
python-spain/documentacion pull request #39
Opened 2020-05-17 11:25 UTC by raulcd

Acta Mayo.

2020-05-17 11:56 UTC, XaviTorello requested changes
Lo veo bien, muchas gracias @raulcd! :beers:

Cómo veís si cambiamos los nombres por los alias de GH?

2020-05-17 13:36 UTC, bameda commented
A mi  no me parece mal. Pero vamos, voto por lo que resulte más cómodo para @raulcd. Supongo que para utilizar los usernames de github deberá conocerlos de antemano, puesto que en su pc no dispone del autocompletado como sucede en la interfaz de github y puede resultar más complicado.

2020-05-17 15:18 UTC, dukebody approved these changes
Contenito todo OK, sólo arreglos ortográficos.

2020-05-17 15:18 UTC, dukebody commented on actas/acta-2020-05-05.rst
> +- Maria Antonia se encarga de subir el nuevo reglament a Github.
```suggestion
- Maria Antonia se encarga de subir el nuevo reglamento a Github.
```

2020-05-17 15:18 UTC, dukebody commented on actas/acta-2020-05-05.rst
> +Sin Ruegos ni preguntas.
```suggestion
Sin ruegos ni preguntas.
```

2020-05-17 15:21 UTC, dukebody commented
> Cómo veís si cambiamos los nombres por los alias de GH?

No me parece mal si GH hace algún tipo de enlazado automático que valga para algo, pero si hay que hacerlo a mano y no enlaza con nada en otro sitio automáticamente, no sé si aporta mucho. ¿Con qué propósito lo proponías tú @XaviTorello ?

2020-06-22 09:20 UTC, raulcd commented
Mergeo ésto que es la de Mayo, he creado links en rst para los usernames.

2020-06-22 09:21 UTC, merged