Acta de la reunión de Julio.
python-spain/documentacion pull request #4
Opened 2018-07-21 14:39 UTC by maigimenez

2018-07-22 12:06 UTC, mariocj89 requested changes
Genial! solo un mini typo

2018-07-22 12:06 UTC, mariocj89 commented on acta-2018-07-04.rst
> + Mario propone crear un canal para Asociaciones en *the-psf* y la junta lo secundapor unanimidad.
`secundapor ` -> `secunda por `

2018-07-22 20:36 UTC, astrojuanlu approved these changes
Aparte de lo que ha dicho @mariocj89, OK!

2018-09-17 13:44 UTC, astrojuanlu requested changes
Algunos errores tipográficos y una puntualización

2018-09-17 13:44 UTC, Juanlu001 commented on acta-2018-07-23-socias.rst
> +3.1. Coutas
*Cuotas

2018-09-17 13:44 UTC, Juanlu001 commented on acta-2018-07-23-socias.rst
> + Por lo tanto decidimos que deben existir dos niveles de socios y socias. Unos que paguen la cuota de membresia como ha venido sucendiendo y en nuevo tipo de miembro de la asociación que no pague cuo
*sucediendo

2018-09-17 13:44 UTC, Juanlu001 commented on acta-2018-07-23-socias.rst
> + - Se trabajará en un documento que expecifique las ventajas de ser socia.
*especifique

2018-09-17 13:44 UTC, Juanlu001 commented on acta-2018-07-04.rst
> + Se ha iniciado la llamada a sedes para la organización de la PyConES 2019 y están llegando confirmaciones oficiales informales que avanzan favorablemente.
Confirmaciones ~oficiales~ informales :) De momento no hay nada oficial

2018-09-17 13:51 UTC, maigimenez commented on acta-2018-07-04.rst
> + Mario propone crear un canal para Asociaciones en *the-psf* y la junta lo secundapor unanimidad.
Solucionado!

2018-09-17 13:52 UTC, maigimenez commented on acta-2018-07-23-socias.rst
> +3.1. Coutas
Hecho!

2018-09-17 13:53 UTC, maigimenez commented on acta-2018-07-04.rst
> + Se ha iniciado la llamada a sedes para la organización de la PyConES 2019 y están llegando confirmaciones oficiales informales que avanzan favorablemente.
Toooda la razón. Cambio aplicado

2018-09-17 13:54 UTC, maigimenez commented on acta-2018-07-23-socias.rst
> + - Se trabajará en un documento que expecifique las ventajas de ser socia.
Cambio aplicado.

2018-09-17 13:56 UTC, maigimenez commented on acta-2018-07-23-socias.rst
> + Por lo tanto decidimos que deben existir dos niveles de socios y socias. Unos que paguen la cuota de membresia como ha venido sucendiendo y en nuevo tipo de miembro de la asociación que no pague cuo
Aplicado

2018-09-17 14:29 UTC, astrojuanlu approved these changes

2018-09-22 11:30 UTC, Juanlu001 commented
Los cambios que pidió @mariocj89 ya están resueltos así que voy a mergear esto.

2018-09-22 11:30 UTC, merged