Re-escritura estatutos
python-spain/documentacion pull request #48
Opened 2021-01-13 18:06 UTC by yamila-moreno

Este PR contiene los cambios en la redacción de los estatutos para que estén redactados de forma inclusiva.

2021-01-17 16:22 UTC, dukebody requested changes
¡Poca cosa, pero va por buen camino!

2021-01-17 16:22 UTC, dukebody commented on estatutos.rst
> + - Mantener una presencia en internet que facilite la difusión de la Asociacion y sus actividades, así como referencia y consulta para socios y socias.
```suggestion
 - Mantener una presencia en Internet que facilite la difusión de la Asociación y sus actividades, así como servir de referencia y consulta para socios y socias.
```

2021-01-17 16:22 UTC, dukebody commented on estatutos.rst
> + d. *Miembros*, que serán aquellas personas afines a la Asociación que colaboren esporádicamente con la misma pero sin una vinculación permanente.
"Miembros y miembras"?

2021-01-17 16:22 UTC, dukebody commented on estatutos.rst
>  **Artículo 6.** Podrán pertenecer a la Asociación aquellas personas físicas que sean mayores de edad con capacidad de obrar y no sujetas a condición legal que lo impida y aquellas personas jurídicas,
Aquí se pone "Reglamento de Régimen Interno" con mayúsculas, pero en otros sitios aparece todo en minúsculas. Hay que decidir una forma y ser consistente.

2021-01-17 16:22 UTC, dukebody commented on estatutos.rst
> + f. Hacer sugerencias a la Junta Directiva en orden al mejor cumplimiento de los fines de la Asociación.
Va más allá de cambiar solamente para lenguaje inclusivo, pero cambiaría para que se entienda mejor:
```suggestion
 f. Hacer sugerencias a la Junta Directiva para contribuir al mejor cumplimiento de los fines de la Asociación.
```

2021-01-27 19:09 UTC, yamila-moreno commented on estatutos.rst
> + d. *Miembros*, que serán aquellas personas afines a la Asociación que colaboren esporádicamente con la misma pero sin una vinculación permanente.
no lo he resuelto aún, sigo pensando :)

2021-01-27 19:09 UTC, yamila-moreno commented on estatutos.rst
>  **Artículo 6.** Podrán pertenecer a la Asociación aquellas personas físicas que sean mayores de edad con capacidad de obrar y no sujetas a condición legal que lo impida y aquellas personas jurídicas,
okis! (fuera de scope, pero oki :P)

2021-02-21 09:02 UTC, dukebody commented on estatutos.rst
> +Sólo los socios y socias de número podrán formar parte de la Junta Directiva, que estará compuesta por: Presidencia, Vicepresidencia, Secretaría, Tesorería y opcionalmente una persona en Vocalía, hab
Aquí se cambia el significado. Puede haber una o más personas en la vocalía, por lo que yo diría "opcionalmente una o más personas en Vocalía".

2021-02-21 09:05 UTC, dukebody commented on estatutos.rst
> +**Artículo 22.** Producida una vacante, provisionalmente, la Junta Directiva podrá designar a otro integrante de la misma para su sustitución o bien designar a algún socio o socia que voluntariamente
"otro/a integrante"?

2021-02-21 09:06 UTC, dukebody commented on estatutos.rst
> +**Artículo 24.** La Junta Directiva se reunirá cuantas veces lo determine Presidencia o a iniciativa o petición de tres de sus integrantes. Quedará constituida cuando asista la mitad más uno de sus i
Quizá "su Presidencia" ya que se refiere a la presidencia de la Junta Directiva, no una "Presidencia" genérica.

2021-02-21 09:08 UTC, dukebody commented on estatutos.rst
> + b. Efectuar la convocatoria de las sesiones de la Junta Directiva y Asamblea, por orden de Presidencia, así como las citaciones de los integrantes de aquélla y socios y socias de ésta.
Igual aquí: quizá deberíamos calificar la "Presidencia" escribiendo "por orden de la Presidencia" en lugar de "por orden de Presidencia", ya que se refiere a una Presidencia concreta, ¿o no? No estoy seguro, seguro que tú sabes más @yamila-moreno .

2021-02-21 09:09 UTC, dukebody commented on estatutos.rst
> + b. Efectuar la convocatoria de las sesiones de la Junta Directiva y Asamblea, por orden de Presidencia, así como las citaciones de los integrantes de aquélla y socios y socias de ésta.
"los y las integrantes"?

2021-02-21 09:11 UTC, dukebody commented on estatutos.rst
> + c. Recibir los actos de comunicación de los integrantes de la Junta Directiva con relación a ésta y de los socios y socias y, por tanto, las notificaciones, peticiones de datos, rectificaciones, cer
"los y las integrantes"?

2021-02-21 09:16 UTC, dukebody commented on estatutos.rst
> +En los casos de ausencia o enfermedad y, en general, cuando concurra alguna causa justificada, el cargo de Secretaría será sustituido por el integrante de la Junta Directiva que indique Presidencia.
"el/la integrante"?

2021-02-22 16:29 UTC, yamila-moreno commented on estatutos.rst
> +Sólo los socios y socias de número podrán formar parte de la Junta Directiva, que estará compuesta por: Presidencia, Vicepresidencia, Secretaría, Tesorería y opcionalmente una persona en Vocalía, hab
tienes razón, me colé. ¡gracias!

2021-02-22 16:32 UTC, yamila-moreno commented on estatutos.rst
> +**Artículo 22.** Producida una vacante, provisionalmente, la Junta Directiva podrá designar a otro integrante de la misma para su sustitución o bien designar a algún socio o socia que voluntariamente
y "podrá designar a cualquiera de las personas que formen parte de la misma" ?

2021-02-22 16:33 UTC, yamila-moreno commented on estatutos.rst
> +**Artículo 24.** La Junta Directiva se reunirá cuantas veces lo determine Presidencia o a iniciativa o petición de tres de sus integrantes. Quedará constituida cuando asista la mitad más uno de sus i
le doy una vuelta, pero creo que es más correcto "Presidencia" que "su Presidencia" por el nivel de abstracción que representa.

2021-02-22 16:34 UTC, yamila-moreno commented on estatutos.rst
> + b. Efectuar la convocatoria de las sesiones de la Junta Directiva y Asamblea, por orden de Presidencia, así como las citaciones de los integrantes de aquélla y socios y socias de ésta.
fixed!

2021-02-22 16:34 UTC, yamila-moreno commented on estatutos.rst
> + c. Recibir los actos de comunicación de los integrantes de la Junta Directiva con relación a ésta y de los socios y socias y, por tanto, las notificaciones, peticiones de datos, rectificaciones, cer
fixed!

2021-02-22 16:35 UTC, yamila-moreno commented on estatutos.rst
> +En los casos de ausencia o enfermedad y, en general, cuando concurra alguna causa justificada, el cargo de Secretaría será sustituido por el integrante de la Junta Directiva que indique Presidencia.
fixed!

2021-03-20 15:25 UTC, dukebody requested changes

2021-03-20 15:25 UTC, dukebody commented on estatutos.rst
> +**Artículo 20.** Para pertenecer a la Junta Directiva serán requisitos imprescindibles: ser mayor de edad, ser socio o socia de número, estar en pleno uso de los derechos civiles y no estar incurso e
```suggestion
**Artículo 20.** Para pertenecer a la Junta Directiva serán requisitos imprescindibles: ser mayor de edad, ser socio o socia de número, estar en pleno uso de los derechos civiles y no estar incurso o incursa en los motivos de incompatibilidad establecidos en la legislación vigente.
```

2021-03-20 15:25 UTC, dukebody commented on estatutos.rst
> +**Artículo 22.** Producida una vacante, provisionalmente, la Junta Directiva podrá designar a otro integrante de la misma para su sustitución o bien designar a algún socio o socia que voluntariamente
Por mí OK este último cambio que propones @yamila-moreno

2021-03-20 15:25 UTC, dukebody commented on estatutos.rst
>  **Artículo 23.** Los miembros de la Junta Directiva cesarán en sus respectivos cargos por las siguientes causas:
```suggestion
**Artículo 23.** Las personas integrantes de la Junta Directiva cesarán en sus respectivos cargos por las siguientes causas:
```

2021-03-20 15:25 UTC, dukebody commented on estatutos.rst
>   g. Por la pérdida de la condición de socio de número.
```suggestion
 g. Por la pérdida de la condición de socio o socia de número.
```

2021-03-20 15:25 UTC, dukebody commented on estatutos.rst
> +**Artículo 26.** El Presidente o Presidenta de la Junta Directiva tendrá las siguientes atribuciones:
¿Deberíamos usar siempre "Presidencia", "Vicepresidencia", etc. en vez de "Presidente o Presidenta", "Vicepresidente o Vicepresidenta"?

2021-03-20 15:25 UTC, dukebody commented on estatutos.rst
> + c. Recibir los actos de comunicación de los integrantes de la Junta Directiva con relación a ésta y de los socios y socias y, por tanto, las notificaciones, peticiones de datos, rectificaciones, cer
```suggestion
 c. Recibir los actos de comunicación de los y las integrantes de la Junta Directiva con relación a ésta y de los socios y socias y, por tanto, las notificaciones, peticiones de datos, rectificaciones, certificaciones o cualquiera otra clase de escritos de los que deba tener conocimiento.
```

2021-03-20 15:25 UTC, dukebody commented on estatutos.rst
> + d. Llevará los libros de la Asociación legalmente establecidos, a excepción de los libros de contabilidad, y el fichero de socios, y custodiará la documentación de la entidad, haciendo que se cursen
```suggestion
 d. Llevará los libros de la Asociación legalmente establecidos, a excepción de los libros de contabilidad, y el fichero de socios/as, y custodiará la documentación de la entidad, haciendo que se cursen las comunicaciones sobre designación de Juntas Directivas y demás acuerdos sociales inscribibles en los Registros correspondientes, así como el cumplimiento de las obligaciones documentales en los términos que legalmente correspondan.
```

2021-03-23 18:16 UTC, yamila-moreno commented on estatutos.rst
> + b. Efectuar la convocatoria de las sesiones de la Junta Directiva y Asamblea, por orden de Presidencia, así como las citaciones de los integrantes de aquélla y socios y socias de ésta.
oks

2021-03-23 18:17 UTC, yamila-moreno commented on estatutos.rst
> +**Artículo 20.** Para pertenecer a la Junta Directiva serán requisitos imprescindibles: ser mayor de edad, ser socio o socia de número, estar en pleno uso de los derechos civiles y no estar incurso e
He preferido deja "y no incurrir en los motivos de incompatibilidad"

2021-03-23 18:18 UTC, yamila-moreno commented on estatutos.rst
>  **Artículo 23.** Los miembros de la Junta Directiva cesarán en sus respectivos cargos por las siguientes causas:
"Las personas que integran la Junta Directiva" creo que se lee mejor.

2021-03-23 18:19 UTC, yamila-moreno commented on estatutos.rst
> +**Artículo 26.** El Presidente o Presidenta de la Junta Directiva tendrá las siguientes atribuciones:
lo veo una cuestión de estilo; me pareció apropiado variar, pero es una preferencia soft; si tienes predilección por la consistencia, lo pongo todo en modo genérico sin duplicar.

2021-03-23 18:20 UTC, yamila-moreno commented on estatutos.rst
> + d. Llevará los libros de la Asociación legalmente establecidos, a excepción de los libros de contabilidad, y el fichero de socios, y custodiará la documentación de la entidad, haciendo que se cursen
"socios y socias" como en el resto del docu

2021-03-30 17:52 UTC, cmaureir commented on estatutos.rst
> +**Artículo 26.** El Presidente o Presidenta de la Junta Directiva tendrá las siguientes atribuciones:
+1 a utilizar "Presidencia" y "Vicepresidencia"

2021-03-30 18:07 UTC, cmaureir reviewed
Muchas gracias por todos los cambios @yamila-moreno, dejé un par de comentarios, pero me parece OK como está ahora.

Una sugerencia que dejé es de utilizar quizás una forma del lenguaje aún más amplio, para que todo no sea binario y que podamos incluir a más personas. Me di cuenta que dejar comentarios en cada lugar sería mucho, por lo que si crees que algo así tiene sentido, yo podría dejarte las sugerencias en cada línea y así solo las puedes agregar con clicks, en vez de re-hacer los cambios, de lo contrario, no te preocupes, ya considero que con los cambios que propones, los estatutos tienen mucha mejor pinta :tada: Gracias de nuevo!

2021-03-30 18:07 UTC, cmaureir commented on estatutos.rst
> +**Artículo 7.** Dentro de la Asociación existirán las siguientes clases de membresía:
Si bien "pertenencia a la asociación" y "membresía" cumplen el mismo objetivo, como son estatutos, quizás podemos utilizar la misma palabra para evitar confusión. Ambas me parecen buenas, con lo que quizás acá ponemos:

```suggestion
**Artículo 7.** Dentro de la Asociación existirán las siguientes clases de pertenencia a la asociación:
```
O cambiamos el título a "Membresía"
¿Te parece OK? ¿O crees que es hilar muy fino?
Lo dejo a tu criterio :)

2021-03-30 18:07 UTC, cmaureir commented on estatutos.rst
> + a. *Socios fundadores y socias fundadoras*, que serán quienes participen en el acto de constitución de la Asociación.
Quizás para no usar el masculino y femenino, podríamos utilizar "Membresía fundacional", y con los demás "membresía de número", "membresía de honor", etc, etc...así podríamos abarcar a la gente no binaria, sin el uso de la "e".
¿Qué te parece? Si crees que es mucho trabajo, y así está OK, no tengo problema.

2021-03-31 06:48 UTC, yamila-moreno commented on estatutos.rst
> +**Artículo 26.** El Presidente o Presidenta de la Junta Directiva tendrá las siguientes atribuciones:
okis, lo cambio en todos los casos, pues

2021-03-31 06:52 UTC, yamila-moreno commented on estatutos.rst
> + a. *Socios fundadores y socias fundadoras*, que serán quienes participen en el acto de constitución de la Asociación.
hola @cmaureir no sé si es por GH o por qué, pero veo tu comentario sobre "membresía" en el contexto de otros cambios así que no entiendo bien.

el tema de "membresía" lo valoré y descarté pues genera una inconsistencia semántica ya que "membresía" y "miembro" comparten raíz, y resulta que los "miembros" son una categoría de pertenencia. Si usamos membresía, sería equivalente a: 
- los socios son un tipo de miembro
- los miembros son un tipo de miembro
cuando además, los socios son la figura principal. Por esto lo descarté.

el cambio de "aquellos que" a "quienes" me parece guay, lo cambio!

2021-03-31 07:00 UTC, yamila-moreno commented on estatutos.rst
> +**Artículo 7.** Dentro de la Asociación existirán las siguientes clases de membresía:
vale, acabo de ver que es se me coló una "membresía" donde iba un "pertenencia a la Asociación". corregido!!

2021-03-31 07:01 UTC, yamila-moreno commented
> Muchas gracias por todos los cambios @yamila-moreno, dejé un par de comentarios, pero me parece OK como está ahora.
> 
> Una sugerencia que dejé es de utilizar quizás una forma del lenguaje aún más amplio, para que todo no sea binario y que podamos incluir a más personas. Me di cuenta que dejar comentarios en cada lugar sería mucho, por lo que si crees que algo así tiene sentido, yo podría dejarte las sugerencias en cada línea y así solo las puedes agregar con clicks, en vez de re-hacer los cambios, de lo contrario, no te preocupes, ya considero que con los cambios que propones, los estatutos tienen mucha mejor pinta tada Gracias de nuevo!

En lugar de hacer las propuestas en pequeño, creo que es mejor que comentes el espíritu general con algunos ejemplos y si cuadran, los puedo cambiar fácilmente de una con vim.

2021-03-31 08:25 UTC, cmaureir commented
> > Muchas gracias por todos los cambios @yamila-moreno, dejé un par de comentarios, pero me parece OK como está ahora.
> > Una sugerencia que dejé es de utilizar quizás una forma del lenguaje aún más amplio, para que todo no sea binario y que podamos incluir a más personas. Me di cuenta que dejar comentarios en cada lugar sería mucho, por lo que si crees que algo así tiene sentido, yo podría dejarte las sugerencias en cada línea y así solo las puedes agregar con clicks, en vez de re-hacer los cambios, de lo contrario, no te preocupes, ya considero que con los cambios que propones, los estatutos tienen mucha mejor pinta tada Gracias de nuevo!
> 
> En lugar de hacer las propuestas en pequeño, creo que es mejor que comentes el espíritu general con algunos ejemplos y si cuadran, los puedo cambiar fácilmente de una con vim.

Gracias! No había considerado tu punto respecto a  "Membresía", me parece OK dejarlo así entonces :tada:
Los había hecho inline, pues así puedes "agregarlos uno a uno con un click" y luego haces un commit que los incluye todos, pero si se te hace más facil lo de comentario general, lo tendré presente para la próxima.

2021-04-10 17:51 UTC, dukebody commented
Aprobado en asamblea general!

2021-04-11 15:04 UTC, merged

2021-04-11 15:43 UTC, dukebody commented
@yamila-moreno Quizá podemos hacer un poco de publi de este cambio en Twitter y Discourse. ¿Qué te parece?

2021-04-11 15:59 UTC, yamila-moreno commented
¡buena idea!