Acta Abril
python-spain/documentacion pull request #58
Opened 2021-04-17 09:39 UTC by raulcd

2021-04-17 14:21 UTC, dukebody requested changes
Pequeñísimos cambios.

2021-04-17 14:21 UTC, dukebody commented on actas/acta-2021-04-13.rst
> +  - Se acuerda que se permitirán peticiones de cuenta de correo siempre que tengan que ver con el nombre/apellidos de las socias que lo solicitan.
Quizá para que quede un poquito más claro:
```suggestion
  - Se acuerda que se permitirán peticiones de nombres de cuenta de correo distintos del estándar siempre que tengan que ver con el nombre/apellidos de las socias que lo solicitan.
```

2021-04-17 14:21 UTC, dukebody commented on actas/acta-2021-04-13.rst
> +- Se acuerda modificar ya los estatutos con los cambios aprobados y modificar la sede una vez se tengan más datos. Actualmente no se recibe prácticamente correspondencia y se puede cambiar la sede en
```suggestion
- Se acuerda modificar ya los estatutos con los cambios aprobados y modificar la sede una vez se tengan más datos. Actualmente no se recibe prácticamente correspondencia y se puede cambiar el domicilio fiscal en Hacienda en cuanto tengamos nueva dirección sin requerir cambio de estatutos.
```

2021-04-17 14:21 UTC, dukebody commented on actas/acta-2021-04-13.rst
> +.. _XaviTorello: https://github.com/XaviTorello
(opcional porque no creo que haga mal) Xavi y Antonia no estuvieron en la Junta, por lo que probablemente no hace falta enlazarlos aquí.

2021-04-18 09:21 UTC, raulcd commented on actas/acta-2021-04-13.rst
> +.. _XaviTorello: https://github.com/XaviTorello
Me guesta tenerlos siempre ya que cuando creo una nueva acta suelo copiar de la anterior y así ya tengo los enlaces.

2021-04-18 09:38 UTC, dukebody approved these changes

2021-04-18 09:38 UTC, merged