Acta de octubre para revisar.
python-spain/documentacion pull request #9
Opened 2018-10-19 09:54 UTC by maigimenez

Majers, ahora si, perdonad todo el jaleo y muchas gracias a Pablo :)

2018-10-20 17:18 UTC, mariocj89 approved these changes

2018-10-20 17:18 UTC, mariocj89 commented on acta-2018-10-10.rst
> + En primer lugar destacar que los miembros de los grupos de trabajo deberán ser miembros a su vez de la Asociación de Python España. Asimismo, cada tres meses como mínimo se reunirán los miembros de
Quizas, al ser esta la primera vez que se menciona miembros, decir "miembros o socios"?

2018-10-20 17:18 UTC, mariocj89 commented on acta-2018-10-10.rst
> +   - Información sobre cómo aprender python.
`Python` 😛

2018-10-20 17:18 UTC, mariocj89 commented on acta-2018-10-10.rst
> +   - Información sobre socios y socias, así como un proceso simple que permita asociarse.
Quizas tambien sobre el nuevo "tipo" de miembros no?

2018-10-22 13:34 UTC, maigimenez commented on acta-2018-10-10.rst
> + En primer lugar destacar que los miembros de los grupos de trabajo deberán ser miembros a su vez de la Asociación de Python España. Asimismo, cada tres meses como mínimo se reunirán los miembros de
Es verdad que queda un poco confuso, porque son los miembros de los grupos de trabajo, que pueden ser miembros o socios de la Asociación. Había puesto miembros porque era la cota inferior, pero tienes mucha razón en que sería mejor dejarlo de manera explícita.

2018-10-22 13:36 UTC, maigimenez commented on acta-2018-10-10.rst
> +   - Información sobre cómo aprender python.
¡Que susto con este comentario! Creía que la había liado mucho más. Pero tienes toda la razón.

2018-10-22 13:38 UTC, maigimenez commented on acta-2018-10-10.rst
> +   - Información sobre socios y socias, así como un proceso simple que permita asociarse.
¡Correcto! También la información de los miembros de la asociación deberían estar.

2018-10-22 14:40 UTC, mariocj89 approved these changes

2018-10-22 14:53 UTC, astrojuanlu requested changes
Nitpicks de última hora que github no mostró porque todo está roto :pray:

2018-10-22 14:53 UTC, astrojuanlu commented on acta-2018-10-10.rst
> + Luís Garcia Merino                82
```suggestion
 Luis Garcia Merino                82
```

2018-10-22 14:53 UTC, astrojuanlu commented on acta-2018-10-10.rst
> + Ivan José Martín                            97
```suggestion
 Iván José Martín                            97
```

2018-10-22 14:53 UTC, astrojuanlu commented on acta-2018-10-10.rst
> +  - Acta monográfica de sobre socias.
```suggestion
  - Acta monográfica sobre socias. 
```

2018-10-22 14:53 UTC, astrojuanlu commented on acta-2018-10-10.rst
> + En primer lugar destacar que los miembros de los grupos de trabajo deberán ser miembros a su vez de la Asociación de Python España. Asimismo, cada tres meses como mínimo se reunirán los miembros de
:+1: Y en realidad tendríamos que preparar una propuesta de cambio de estatutos y/o reglamento para poder incorporar esos miembros que no pagan, ¿no?

2018-10-22 15:30 UTC, astrojuanlu approved these changes

2018-10-22 15:30 UTC, merged

2018-10-22 17:02 UTC, XaviTorello commented on acta-2018-10-10.rst
> + Xavier Torrelló, organizador de Girona está empezando a trabajar en una alternativa para gestionar los grupos locales. En particular, disponer de una alternativa a meetup nos parece muy interesante.
Torelló! xDD

2018-10-22 17:03 UTC, XaviTorello commented on acta-2018-10-10.rst
> +Se aprueba por unanimidad la ayuda solicitada por Python Girona para picoteo después de las reuniones que realizan periódicamente, así como los 300 € solicitados por la comunidad de Granada para orga
Muchas gracias!